replicaCount: 1

labels:
  app: flask-app

deployment:
  name: hivebox-deployment

container:
  name: hivebox
  port: 5000

image:
  repository: hivebox-img
  tag: 88
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  port: 5000
  name: hivebox-service
  type: ClusterIP

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true  
  className: "nginx"
  annotations: {
     prometheus.io/scrape: "true",      # Enable Prometheus scraping
     prometheus.io/port: "PORT",        # Replace with actual port
     prometheus.io/path: "/metrics"     # Path to scrape metrics 
  }
  hosts:
    - host: hivebox.testing
      http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service: 
            name: hivebox-service
            port: 5000

    - host: minio.testing
      http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-release-minio-service
            port:
              number: 9001

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

