apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-extra-scrape-config
  namespace: default
data:
  extra-scrape-configs.yaml: |
    - job_name: 'hivebox'
      metrics_path: /metrics
      static_configs:
        - targets: ['hivebox-service.default.svc.cluster.local:5000']