replicaCount: 1

image:
  repository: valkey/valkey
  tag: "latest"
  pullPolicy: Never

service:
  name: valkey-service
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  # storageClass: gp2
  accessMode: ReadWriteOnce
  size: 1Gi
  
labels:
  app: valkey

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
