---
- name: Update Kuberntes Cluster
  hosts: localhost
  become: false   # Don't need root permission, i already have it with user "Khaled"
  vars:
    kind_node: kind-control-plane
    image_name: "{{ IMAGE_NAME }}"
    image_tag: "{{ IMAGE_TAG }}"
    manifest_file: ../Kubernetes/Flask-Deloyment.yaml
    oldImageID: "{{ oldImageID }}"

  tasks:

    - name: Update image tag in Kubernetes Manifest using sedCommand
      shell: |
        sed -i "s|\(image: {{ image_name }}:\).*|\1{{ image_tag }}|" {{ manifest_file }}
      register: sed_output

    - name: Show sed output (if any)
      debug:
        var: sed_output.stdout

    - name: Delete image using crictl inside Kind node
      shell: |
        docker exec {{ kind_node }} crictl rmi {{ oldImageID }}
      register: delete_output
      ignore_errors: true

    - name: Show crictl delete output
      debug:
        var: delete_output.stdout_lines

    - name: Load the new image to KinD Cluster
      shell: kind load docker-image "{{ image_name }}:{{ image_tag }}"

    - name: List all images to ensure the new image loaded successfully
      shell: docker exec {{ kind_node }} crictl images | grep -i {{ image_name }}
