{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.labels.app }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  #storageClassName: {{ .Values.persistence.storageClass }}     # Locally
  storageClassName: gp2     # AWS-EKS 
{{- end }}
