apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hivebox-chart.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
  labels:
    app: hivebox
spec:
  ingressClassName: nginx
  rules:
    - host: hivebox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-service
                port:
                  number: 5000

    - host: minio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-release-minio-service
                port:
                  number: 9001
