apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hivebox-chart.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
  labels:
    app: hivebox
spec:
  ingressClassName: nginx
  rules:
    - host: hivebox.testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-service
                port:
                  number: 5000

    - host: minio.testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-release-minio-service
                port:
                  number: 9001

    # - host: prometheus.local
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: prometheus-kube-prometheus-prometheus
    #             port:
    #               number: 9090

    # - host: grafana.local
    #   http:
    #     paths:
    #     - path: /
    #       pathType: Prefix
    #       backend:
    #         service:
    #           name: grafana
    #           port:
    #             number: 80
