apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "hivebox-chart.fullname" .) }}
  labels:
    {{- include "hivebox-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hivebox-chart.selectorLabels" . | nindent 4 }}
